const ImagesPath = {
  splashIphone: require("../../assetes/img/hc_splash_screen_background_iphon.png"),
  splashIpad: require("../../assetes/img/hc_splash_screen_background.png"),
  backgroundPage: require("../../assetes/img/hc_background.png"),
  backgroundHeaderImg: require("../../assetes/img/hc_header_back.png"),
  menuIconHome: require("../../assetes/img/hc_home_menu.png"),
  menuIconUser: require("../../assetes/img/hc_user_menu.png"),
  menuIconSetting: require("../../assetes/img/hc_setting.png"),
  menuIconHomeActive: require("../../assetes/img/hc_home_menu_unactive.png"),
  menuIconUserActive: require("../../assetes/img/hc_user_menu_unactive.png"),
  menuIconSettingActive: require("../../assetes/img/hc_setting_unactive.png"),
  iconMicrophon: require("../../assetes/img/hc_microphon.png"),
  iconBack: require("../../assetes/img/hc_header_icon_back.png"),
  iconTick: require("../../assetes/img/hc_tick_items.png"),
  iconSettingHelp: require("../../assetes/img/hc_help_setting.png"),
  iconSettingSound: require("../../assetes/img/hc_sound_setting.png"),
  iconSettingLanguege: require("../../assetes/img/hc_languege_setting.png"),
  iconSettingNotification: require("../../assetes/img/hc_notification_setting.png"),
  iconSettingVibrate: require("../../assetes/img/hc_vibrate_setting.png"),
  iconEdit: require("../../assetes/img/hc_icon_edit.png"),
  iconLanguegeEng: require("../../assetes/img/hc_lang_eng.png"),
  iconLanguegeSpan: require("../../assetes/img/hc_lang_spanish.png"),
  iconLanguegeFrenc: require("../../assetes/img/hc_lang_frenc.png"),
  iconLanguegeGerman: require("../../assetes/img/hc_lang_gemany.png"),
  iconDarkTick: require("../../assetes/img/hc_tich_dark.png"),
  imageBgRightScanner: require("../../assetes/img/hc_background_scanner_right.png"),
  imageBgBottomScanner: require("../../assetes/img/hc_background_scanner.png"),
  iconArrowRight: require("../../assetes/img/hc_icone_right.png"),
  img1: require("../../assetes/img/img1.png"),
  img2: require("../../assetes/img/img2.png"),
  img3: require("../../assetes/img/img3.png"),
  img4: require("../../assetes/img/img4.png"),
  img5: require("../../assetes/img/img5.png"),
  img6: require("../../assetes/img/img6.png"),
  img7: require("../../assetes/img/img7.png"),
  img8: require("../../assetes/img/img8.png"),
  img10: require("../../assetes/img/img10.png"),
  img11: require("../../assetes/img/img11.png"),
  img12: require("../../assetes/img/img12.png"),
  img13: require("../../assetes/img/img13.png"),
  img14: require("../../assetes/img/img14.png"),
  img15: require("../../assetes/img/img15.png"),
  img16: require("../../assetes/img/img16.png"),
  img17: require("../../assetes/img/img17.png"),
  img18: require("../../assetes/img/img18.png"),
};

export default ImagesPath;
